name: Manual Deploy to DEV Server

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy"
        required: false
        default: "dev"
      remote_directory:
        description: "Remote directory for deployment"
        required: false
        default: "/DEV/Index.html"
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up SSH key
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: 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

    # Step 3: Sync files using rsync
    - name: Deploy files via rsync
      run: |
        rsync -avz --delete \
          -e "ssh -o StrictHostKeyChecking=no" \
          ./ jumaojmy@50.6.153.228:DEV
